# -*- coding: utf-8 -*-
"""NamedEntityRecognitionusingSpacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WD17ZoAd0aOWwOqJEOHaWiVgIEBGnvqU
"""

import spacy

!python -m spacy download en_core_web_lg

nlp = spacy.load("en_core_web_lg")

nlp.pipe_names

doc=nlp("Tesla Inc is going to acquire twitter for $45 billion")
for ents in doc.ents:
  print(ents.text,"|",ents.label_)

from spacy import displacy
displacy.render(doc,style="ent")

nlp.pipe_labels['ner']

doc=nlp("Nicolo Tesla was a great scientist but Elon Musk invented Tesla Inc")
for ents in doc.ents:
  print(ents.text,"|",ents.label_)

text="My company lost  to johnson & johnson"

nlp=spacy.load("en_core_web_lg")

ruler=nlp.add_pipe("entity_ruler",before="ner")

patterns= [ {"label": "COMPETITOR", "pattern": [{"LOWER": {"IN": ["pfizer", "moderna", "johnson & johnson", "astrazeneca", "gsk", "novartis"]}}]},

    # Life Insurance Companies
    {"label": "COMPETITOR", "pattern": [{"LOWER": {"IN": ["aig", "prudential", "metlife", "lic", "hdfc life", "max life"]}}]},

    # Mutual Fund Companies
    {"label": "COMPETITOR", "pattern": [{"LOWER": {"IN": ["vanguard", "blackrock", "fidelity", "hdfc mutual fund", "icici prudential"]}}]},

    # NBFC & Lending Companies
    {"label": "COMPETITOR", "pattern": [{"LOWER": {"IN": ["bajaj finance", "shriram transport", "mahindra finance", "tata capital", "l&t finance"]}}]},

    {"label": "FINANCIAL_METRIC", "pattern": [{"LOWER": {"IN": ["revenue", "gross profit", "net profit", "ebitda", "operating income"]}}]},

    # Growth Metrics
    {"label": "FINANCIAL_METRIC", "pattern": [{"LOWER": {"IN": ["yoy growth", "qoq growth", "profit margin", "expense ratio", "roe", "roa", "pe ratio"]}}]},

    # Assets & Liabilities
    {"label": "FINANCIAL_METRIC", "pattern": [{"LOWER": {"IN": ["aum", "assets under management", "total assets", "net worth", "debt to equity"]}}]},


    {"label": "M_A_ACTIVITY", "pattern": [{"LOWER": {"IN": ["merger", "acquisition", "takeover", "joint venture", "stake purchase", "buyout"]}}]},

    # Product Launches & Services
    {"label": "PRODUCT_LAUNCH", "pattern": [{"LOWER": {"IN": ["new product", "service launch", "market expansion", "product line extension"]}}]},

    # Partnerships & Collaborations
    {"label": "PARTNERSHIP", "pattern": [{"LOWER": {"IN": ["strategic alliance", "collaboration", "partnership agreement", "joint venture"]}}]},

    # Market Position & Customer Base
    {"label": "MARKET_POSITION", "pattern": [{"LOWER": {"IN": ["market share", "customer base", "client acquisition", "industry ranking"]}}]},

    # Regulatory Approvals & Compliance
    {"label": "REGULATORY_EVENT", "pattern": [{"LOWER": {"IN": ["fda approval", "sec filing", "regulatory compliance", "government approval", "audit results"]}}]},


    {"label": "STOCK_MOVEMENT", "pattern": [{"LOWER": {"IN": ["stock price", "market cap", "ipo", "dividends", "shareholder return"]}}]},

    # Investment & Fundraising
    {"label": "INVESTMENT", "pattern": [{"LOWER": {"IN": ["investment round", "venture capital funding", "private equity", "angel investment"]}}]},


    {"label": "SUPPLY_CHAIN_ISSUE", "pattern": [{"LOWER": {"IN": ["supply chain disruption", "logistics issue", "raw material shortage", "supplier bankruptcy"]}}]},


    {"label": "LEGAL_DISPUTE", "pattern": [{"LOWER": {"IN": ["lawsuit", "legal battle", "regulatory fine", "compliance violation", "antitrust investigation"]}}]},


    {"label": "CYBERSECURITY_RISK", "pattern": [{"LOWER": {"IN": ["data breach", "hacking incident", "cybersecurity vulnerability", "ransomware attack"]}}]},


    {"label": "HIRING_ACTIVITY", "pattern": [{"LOWER": {"IN": ["hiring surge", "mass layoffs", "restructuring", "executive appointment", "leadership change"]}}]},


    {"label": "MARKETING_STRATEGY", "pattern": [{"LOWER": {"IN": ["brand repositioning", "ad campaign", "customer engagement", "pricing strategy"]}}]},


    {"label": "R_D_ACTIVITY", "pattern": [{"LOWER": {"IN": ["patent filing", "r&d spending", "innovation hub", "technology development"]}}]},
]

ruler.add_patterns(patterns)

doc=nlp(text)
# Get all unique labels from your patterns AND the default NER labels
all_labels = set(pat['label'] for pat in patterns) | set(nlp.pipe_labels['ner'])
entities = {label: [] for label in all_labels}

for ent in doc.ents:
  entities[ent.label_].append(ent.text)

print(entities)

