# -*- coding: utf-8 -*-
"""Parsing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDZi7xFBBIwQwoCivz2E2mKARPKz9SnE
"""

!pip install PyPDF2

import PyPDF2
from PyPDF2 import PdfReader

doc=PdfReader('/content/Q2 FY 2024-2025 FINANCIAL RESULT.pdf')

print(doc.metadata)

page=doc.pages[0]

print(page.extract_text())

doc=PdfReader('/content/Q2 FY 2024-2025 FINANCIAL RESULT.pdf')
text=""
for page in doc.pages:
  extracted_text=page.extract_text()
  if extracted_text:
    text+=extracted_text+"\n"

print(text)

