# -*- coding: utf-8 -*-
"""Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_Dl998McoXWKRpJiST67B_sEBr1WoOE
"""

!pip install transformers

from transformers import BartTokenizer
from transformers import BartForConditionalGeneration

tokenizer=BartTokenizer.from_pretrained("facebook/bart-large-cnn")
model=BartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")

def summarize(text):
  input=tokenizer.encode("summarize"+text,return_tensors="pt",max_length=1024,truncation=True)
  summary_ids=model.generate(input,max_length=200,min_length=40,length_penalty=2.0,num_beams=4) # Added num_beams=4 as a placeholder
  output=tokenizer.decode(summary_ids[0],skip_special_tokens=True)
  return output

text="""
Wikipedia is in hot water again. The Maharashtra Cyber Cell has lodged a case against at least four editors of the platform for failing to take down “objectionable” content on Chhatrapati Sambhaji Maharaj, officials said on Friday (February 21).

This comes after a notice was sent to the Wikimedia Foundation, based in the United States’ California, seeking the removal of the content from Wikipedia. However, there was no reply from Wikimedia, a non-profit organisation that hosts the open-source encyclopedia, reported PTI.


"""
summary=summarize(text)
print(summary)

